### ISSUE TITLE
Doesn't install on Nougat

### ISSUE THREAD

**Issue by IzzySoft** [AndreasSE93/android-recents-override#1]
Just the app I'd need – but it doesn't install on Nougat (Android 7), requiring SDK 26 (Oreo/Android 8). The issue with clearing out recents after 6h already exists on N; could you make the APK compatible to it, or is there any show-stopper (API you need that's not yet available on N)?

**Comment by AndreasSE93** [comment]
I don't see any reason it shouldn't work, so I probably just put the wrong version in. I've uploaded a new version to the Xposed repo with minSdkVersion 25.

**Comment by IzzySoft** [comment]
Thanks!

**Comment by IzzySoft** [comment]
OK, had to download and install it manually from the Xposed repo website (somehow the index always fails to update on my device, not being able to deal with a 302 redirect). Works fine on Nougat, as expected :wink:
